#include <stdint.h>

uint8_t WERLD_TILE_TYPE_GROUND = 0;
uint8_t WERLD_TILE_TYPE_WALL   = 1;

unsigned short int WERLD_TILE_PROPERTY_TRAVERSABLE = 1;
/*int WERLD_TILE_PROPERTY_ANOTHER_PROPERTY = 1 << 1;*/
